/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "ROCK?": "石头",
    "Paper Upgrades!": "纸升级！",
    "Lizard Upgrades!": "蜥蜴升级！",
    "Point Upgrades!": "点数升级！",
    "Scissor Upgrades!": "剪刀升级！",
    "Rock Upgrades!": "石头升级！",
    "Spock Upgrades!": "布升级！",
    "Saving": "保存中",
    "Save Game": "保存游戏",
    "SCISSOR": "剪刀",
    "Sell Mode": "出售模式",
    "Speed Run": "快速运行",
    "Speed Run!": "快速运行!",
    "Stats": "统计",
    "Total wins:": "获胜总次数:",
    "Total losses:": "输掉总次数:",
    "Total paper earned:": "赚取的纸张总数:",
    "Tweaks": "微调",
    "UI": "界面",
    "Unlock new point type for Papers, Scissors, and Rocks which are earned by winning with that option (i.e. win with rock and earn rock points).": "解锁“剪刀、布”和“石头”的新点数类型（纸），这些点数类型是通过赢得该选项获得的（例如，赢得石头并获得石头点数）。",
    "WIN": "赢了",
    "WIN!": "赢了!",
    "Win / Loss / Ties": "赢 / 输 / 平局",
    "Rock never loses. It is the ultimate weapon.": "石头永远不会输。它是终极武器。",
    "Selecting Paper will switch to being rock X% of the time.": "选择“纸”会在X%的时间内切换为“石头”。",
    "Selecting Scissor will switch to being rock X% of the time.": "选择“剪刀”会在X%的时间内切换为“石头”。",
    "Selecting Spock will switch to being rock X% of the time.": "选择“布”会在X%的时间内切换为“石头”。",
    "Selecting LIZARD will switch to being rock X% of the time.": "选择“蜥蜴”会在X%的时间内切换为“石头”。",
    "Streak (mulls)": "条纹 (考虑)",
    "TIE": "平局",
    "ROCK ALWAYS WINS!": "石头总会赢",
    "Speed Run Round Limit:": "快速运行回合限制：",
    "The objective is to win! WIN! WIN!": "目标就是赢！赢！赢！",
    "The objective of this game is to earn points by winning games of Paper, Scissor, Rock (that's the right order, don't question it).": "这个游戏的目标是通过赢得“布、剪刀、石头”的游戏来获得点数（这是正确的顺序，不要质疑它）。",
    "Timer:": "计时器:",
    "Ties extend your win streak.": "平局延长你的连胜纪录。",
    "Ties don't break your win streak.": "平局不会打破你的连胜纪录。",
    "WARNING: This is non-reversible and will delete your current save. Recommend you export your save first!": "警告：这是不可逆转的，将删除您当前的保存。建议您先导出您的存档并备份！",
    "WARNING: Your saved game is from an older version!": "警告：您保存的游戏存档来自旧版本！",
    "Welcome to Rock Always Wins Idle!": "欢迎来到 石头总是赢放置！",
    "That said, you do you friend!  Good luck!": "也就是说，你做你的朋友！祝你好运！",
    "Rock always wins. It is unstoppable.": "石头总会赢。这是不可阻挡的。",
    "Use points to speed up the game, earn more points per win, and so on. ": "使用点数来加速游戏，每次获胜获得更多点数，等等。",
    "YOU DID IT! We're adding one more game option now. Good luck!": "你做到了！我们现在增加了一个游戏选项。祝你好运！",
    "Winning with SPOCK selected earns more spocks.": "选择 布 获胜可以获得更多的 布。",
    "Winning with Spock earns ROCKS instead. Convert all current Spocks to Rocks.": "用 布 获胜可以获得 石头。将当前所有 布 转化为 石头",
    "Total ties:": "总计平局:",
    "Total wins with  paper:": "总计用 纸 获胜:",
    "Total wins with scissors:": "总计用 剪刀 获胜:",
    "Total wins with paper:": "总计用 纸 获胜:",
    "Total wins with spock:": "总计用 布 获胜:",
    "Total wins with rock:": "总计用 石头 获胜:",
    "Total wins with lizard:": "总计用 蜥蜴 获胜:",
    "Total time played:": "总计游戏时长:",
    "Total lizards earned:": "总计获得的蜥蜴:",
    "Total pts earned:": "总计获得的点数:",
    "Total pts earned from ties:": "总计通过平局获得的点数:",
    "Total rocks earned:": "总计获得的石头:",
    "Total scissors earned:": "总计获得的剪刀:",
    "Total spocks earned:": "总计获得的布:",
    "Pause": "暂停",
    "Player": "玩家",
    "Points": "点数",
    "NOT ROCK?": "不是石头？",
    "PAPER": "纸",
    "New!": "新!",
    "New Round": "新回合",
    "Mulligans used:": "使用的加击：",
    "New Game": "新游戏",
    "LOSE": "输了",
    "Losing will not break your win streak X number of times.": "失败不会打破你的连胜X次。",
    "Not all game options are created alike (and may not have equal W/L/T ratios). This increases the earnings for the disadvantaged types. Does not work on ties.": "并非所有游戏选项都是相同的（游戏邦注：赢 / 输 / 平局 比率也不相同）。这增加了弱势群体的收入。对平局不起作用。",
    "Points earned": "赚取的点数",
    "Points earned from wins are multiplied by X amount. This amount is summed between each game option type.": "从胜利中获得的点数乘以X。这个数量是在每个游戏选项类型之间的总和。",
    "Game Rules!": "游戏规则！",
    "Game Rules": "游戏规则",
    "Prestige": "声望",
    "Removed": "已移除",
    "Reset Prestige": "重置声望",
    "Features": "功能",
    "Experiments": "实验性",
    "Export Save JSON (Copy)": "导出存档JSON（复制）",
    "Free Mode": "免费模式",
    "HELP!": "帮助！",
    "Game Saved!": "游戏已保存！",
    "Game Stats!": "游戏统计！",
    "Game will go faster.": "游戏会进行得更快。",
    "Game Speed Multiplier": "游戏速度乘数",
    "Hide Game Option Upgrade Purchases": "隐藏游戏选项升级购买",
    "Import Save JSON": "导入存档JSON",
    "Import Save JSON!": "导入存档JSON!",
    "Longest streak:": "最长连胜纪录：",
    "Max Streak:": "最大连胜：",
    "NEW GAME!": "新游戏！",
    "Reset Tripometer": "重置行程计",
    "ROCK": "石头",
    "W / L / T :": "赢 / 输 / 平局 :",
    "Winning with any game option will increase your streak by more each win.": "使用任何游戏选项获胜都会增加你的连胜次数。",
    "Winning with Lizard earns ROCKS instead. Convert all current Lizards to Rocks.": "用蜥蜴获胜可以获得石头。将所有蜥蜴转化为石头。",
    "Winning with LIZARD selected earns more lizards.": "选择蜥蜴获胜可以获得更多蜥蜴。",
    "Winning with Paper earns ROCKS instead. Convert all current Papers to Rocks.": "而用纸获胜则会获得石头。将当前所有纸转换为石头。",
    "Winning with PAPER selected earns more papers.": "通过选择纸获胜，可以获得更多的纸。",
    "Winning with rock multiplies your streak multiplier.": "用石头获胜会增加你的连胜乘数。",
    "Winning with ROCK selected earns more rocks.": "选择石头获胜可以获得更多石头。",
    "Winning with Scissor earns ROCKS instead. Convert all current Scissors to Rocks.": "用剪刀获胜则可以获得石头。将所有当前的剪刀转换为石头。",
    "Winning with SCISSOR selected earns more scissors.": "选择剪刀获胜可以获得更多的剪刀。",
    "(Welcome back!) Game content and save data may not work as expected.": "(欢迎回来!)游戏内容和保存数据可能无法正常工作。",
    "ABORT (IT'S A TRAP!)": "中止（这是个陷阱！）",
    "Are you sure you want to start a new game?": "你确定要开始一个新游戏吗？",
    "Auto-Purchase Upgrades": "自动购买升级",
    "Avg Pts / round:": "平均点数 / 回合:",
    "Avg Pts / sec:": "平均点数 / 秒:",
    "Bot": "电脑",
    "Bug Fixes": "修复Bug",
    "FREE": "免费",
    "Display tripometer": "显示行程计",
    "Highest round points": "最高回合点数",
    "Earn points from ties worth X% of a win.": "在平局中获得X%的胜利点数。",
    "Earn more points for each round won.": "每赢一局就能获得更多的点数。",
    "Earn more points for each round won using the power of paper.": "使用纸的力量，每赢一局就能获得更多的点数。",
    "Earn more points for each consecutive win. This is a cumulative upgrade (i.e. 1 win is 1.05x, 2 wins are 1.10x, etc.).": "每次连续获胜获得更多积分。这是一个累积升级（即1胜是1.05倍，2胜是1.10倍，等等）。",
    "Highest single game points:": "最高单局点数：",
    "I try not to break things, but this game is still in early development. There have been significant games changes since you last played. ": "我尽量避免破坏某些内容，但这款游戏仍处于早期开发阶段。自从你上次玩游戏以来，游戏发生了重大变化。",
    "I would suggest that you start a new game.": "我建议你开始一个新游戏。",
    "Import Save (No Going Back!)": "导入存档（不能回退！）",
    "In case you didn't know: at the end of the day, ROCK ALWAYS WINS!": "如果你不知道的话：在一天结束的时候，石头总会赢！",
    "Increase percent chance of a 'critical win' where you earn 2x points. Wins will have an '!' around them if it was a critical win.": "增加你获得2x点数的“暴击胜利”的几率。胜利时会有一个感叹号“！”如果这一局是暴击胜利。",
    "Increase the speed of the game using the power of scissors.": "使用剪刀的力量增加游戏的速度。",
    "Increase your win streak multiplier by even more! This is a cumulative upgrade (i.e. 1.01x + 1.01x = 1.02x).": "增加你的连胜乘数甚至更多！这是一个累积升级（即1.01x + 1.01x = 1.02x）。",
    "New rules (Settings > Game Rules):": "新规则（设置>游戏规则）：",
    "Prestige into a higher realm. Give up all your upgrades, rocks, and points to play with one more game option. See if rock can achieve victory again.": "声望到更高的领域。放弃你所有的升级，石头，和点数去玩一个更多的游戏选项。看看石头能否再次取得胜利。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Change Log": "更新日志",
    "Convert all Lizard to Rocks: ": "将所有蜥蜴转换为石头：",
    "Level Up! (Reset and unlock a new game option): ": "升级了！（重置并解锁一个新的游戏选项）：",
    "Points:": "点数:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Rock Always Wins: (.+) pts$/, '石头总会赢: $1 点数'],
    [/^Game Option Equalizer: (.+) pts$/, '游戏选项均衡器: $1 点数'],
    [/^Ties Do Not Break Streak: (.+) pts$/, '平局不会打破连胜: $1 点数'],
    [/^Rock Never Loses: (.+) pts$/, '石头永不会输: $1 点数'],
    [/^Unlock Paper\/Scissor\/Rock Points: (.+) pts$/, '解锁纸/剪刀/石头点数: $1 点数'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);